# PROJECT CAPSTONE ADUIN
Dataset Kaggle [Indonesia News Dataset (2025)](https://www.kaggle.com/datasets/sh1zuka/indonesia-news-dataset-2024)

#### Menginstal dan Mengimpor Library yang Dibutuhkan

In [57]:
!pip install PySastrawi

import pandas as pd
import re

Requirement already satisfied: PySastrawi in /usr/local/lib/python3.12/dist-packages (1.2.0)

## Data Wrangling

### Gathering Data

In [58]:
df = pd.read_csv('/content/drive/MyDrive/dataset_kaggle.csv')
print(f"Data awal: {len(df)} baris")

Data awal: 80472 baris

### Assessing Data

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80472 entries, 0 to 80471
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Judul    80472 non-null  object
 1   Waktu    80472 non-null  object
 2   Link     80472 non-null  object
 3   Content  80463 non-null  object
 4   tag1     78023 non-null  object
 5   tag2     77612 non-null  object
 6   tag3     71602 non-null  object
 7   tag4     56856 non-null  object
 8   tag5     35633 non-null  object
 9   source   80472 non-null  object
dtypes: object(10)
memory usage: 6.1+ MB

In [60]:
df.describe()

,Judul,Waktu,Link,Content,tag1,tag2,tag3,tag4,tag5,source
count,80472,80472,80472,80463,78023,77612,71602,56856,35633,80472
unique,67168,26970,67381,67367,18490,24482,26226,24944,18463,3
top,5 Berita Terpopuler Internasional Hari Ini,26 November 2024,https://news.detik.com/berita/d-8058078/menter...,"Baca berita dengan sedikit iklan, klik di sin...",Jakarta,jabodetabek,jabodetabek,jabodetabek,jabodetabek,kompas
freq,7,149,4,5,865,488,915,951,557,35449

In [61]:
df.isnull().sum()

Judul          0
Waktu          0
Link           0
Content        9
tag1        2449
tag2        2860
tag3        8870
tag4       23616
tag5       44839
source         0
dtype: int64

In [62]:
link_contoh = df[df.duplicated(subset=["Link"], keep=False)]["Link"].iloc[0]
print("Link:", link_contoh)
print()
print(df[df["Link"] == link_contoh][["Judul", "Waktu", "source"]])

Link: https://news.detik.com/berita/d-7486691/gempa-m-5-3-guncang-pulau-doi-maluku-utara

                                            Judul  \
1      Gempa M 5,3 Guncang Pulau Doi Maluku Utara
6163   Gempa M 5,3 Guncang Pulau Doi Maluku Utara
73329  Gempa M 5,3 Guncang Pulau Doi Maluku Utara

                              Waktu source
1      Senin, 12 Agu 2024 21:58 WIB  detik
6163   Senin, 12 Agu 2024 21:58 WIB  detik
73329  Senin, 12 Agu 2024 21:58 WIB  detik

In [63]:
duplikat_count = df[df.duplicated(subset=["Link"], keep=False)].groupby("Link").size()

print("Artikel muncul 2x:", (duplikat_count == 2).sum())
print("Artikel muncul 3x:", (duplikat_count == 3).sum())
print("Artikel muncul >3x:", (duplikat_count > 3).sum())
print("Total link unik yang duplikat:", len(duplikat_count))

Artikel muncul 2x: 308
Artikel muncul 3x: 6366
Artikel muncul >3x: 17
Total link unik yang duplikat: 6691

In [64]:
df = df.drop_duplicates(subset=["Link"])
print("Data bersih:", len(df), "baris")

Data bersih: 67381 baris

In [65]:
tag_cols = ['tag1', 'tag2', 'tag3', 'tag4', 'tag5']
df['all_tags'] = df[tag_cols].apply(lambda x: ', '.join(x.dropna().astype(str)), axis=1)

In [66]:
df.head()

,Judul,Waktu,Link,Content,tag1,tag2,tag3,tag4,tag5,source,all_tags
0,"Viral Isu PHK Buruh Gudang Garam, Said Iqbal: ...",6 September 2025,https://nasional.kompas.com/read/2025/09/06/14...,"JAKARTA, KOMPAS.com – Presiden Konfederasi Se...",Said Iqbal,industri rokok,PT Gudang Garam,PHK massal,phk massal 2025 terbaru,kompas,"Said Iqbal, industri rokok, PT Gudang Garam, P..."
1,"Gempa M 5,3 Guncang Pulau Doi Maluku Utara","Senin, 12 Agu 2024 21:58 WIB",https://news.detik.com/berita/d-7486691/gempa-...,"Gempa bumi berkekuatan magnitudo (M) 5,3 mengg...",pulau doi,gempa,NaN,NaN,NaN,detik,"pulau doi, gempa"
2,"Toko Emas Palsu di Riau Dibongkar Polisi, Perh...","Rabu, 30 Jul 2025 22:22 WIB",https://news.detik.com/melindungi-tuah-marwah/...,Satreskrim Polres Bengkalis membongkar praktik...,pemalsuan emas,emas palsu,polres bengkalis,polda riau,melindungi tuah marwah,detik,"pemalsuan emas, emas palsu, polres bengkalis, ..."
3,Minyakita Tak Sesuai Ukuran juga Ditemukan di ...,"Senin, 10 Mar 2025 23:15 WIB",https://news.detik.com/berita/d-7816829/minyak...,Polisi mendatangi salah satu gudang Minyakita ...,minyakita,kudus,NaN,NaN,NaN,detik,"minyakita, kudus"
4,"Pimpin LDP, Sanae Takaichi Calon Kuat PM Perem...",4 Oktober 2025 | 14.00 WIB,https://www.tempo.co/internasional/pimpin-ldp-...,"Baca berita dengan sedikit iklan, klik di sin...",jepang,perdana-menteri,sanae-takaichi,perempuan,ldp,tempo,"jepang, perdana-menteri, sanae-takaichi, perem..."

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67381 entries, 0 to 80471
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Judul     67381 non-null  object
 1   Waktu     67381 non-null  object
 2   Link      67381 non-null  object
 3   Content   67378 non-null  object
 4   tag1      64939 non-null  object
 5   tag2      64725 non-null  object
 6   tag3      60423 non-null  object
 7   tag4      49805 non-null  object
 8   tag5      32264 non-null  object
 9   source    67381 non-null  object
 10  all_tags  67381 non-null  object
dtypes: object(11)
memory usage: 6.2+ MB

### Cleaning Data

In [68]:
def bersihkan_teks(teks):
    if pd.isna(teks):
        return ""
    teks = str(teks).lower() # Mengubah teks menjadi huruf kecil
    teks = re.sub(r'http\S+|www\S+|https\S+', '', teks, flags=re.MULTILINE) # Menghapus link URL
    teks = re.sub(r'[^\w\s]', ' ', teks) # Menghapus tanda baca
    teks = re.sub(r'\s+', ' ', teks).strip() # Menghapus spasi berlebih
    return teks

# Mengaplikasikan fungsi pembersihan ke kolom yang akan dianalisis
df['clean_tags'] = df['all_tags'].apply(bersihkan_teks)
df['clean_judul'] = df['Judul'].apply(bersihkan_teks)
df['clean_konten'] = df['Content'].apply(bersihkan_teks)

In [69]:
df.head()

,Judul,Waktu,Link,Content,tag1,tag2,tag3,tag4,tag5,source,all_tags,clean_tags,clean_judul,clean_konten
0,"Viral Isu PHK Buruh Gudang Garam, Said Iqbal: ...",6 September 2025,https://nasional.kompas.com/read/2025/09/06/14...,"JAKARTA, KOMPAS.com – Presiden Konfederasi Se...",Said Iqbal,industri rokok,PT Gudang Garam,PHK massal,phk massal 2025 terbaru,kompas,"Said Iqbal, industri rokok, PT Gudang Garam, P...",said iqbal industri rokok pt gudang garam phk ...,viral isu phk buruh gudang garam said iqbal su...,jakarta kompas com presiden konfederasi serika...
1,"Gempa M 5,3 Guncang Pulau Doi Maluku Utara","Senin, 12 Agu 2024 21:58 WIB",https://news.detik.com/berita/d-7486691/gempa-...,"Gempa bumi berkekuatan magnitudo (M) 5,3 mengg...",pulau doi,gempa,NaN,NaN,NaN,detik,"pulau doi, gempa",pulau doi gempa,gempa m 5 3 guncang pulau doi maluku utara,gempa bumi berkekuatan magnitudo m 5 3 menggun...
2,"Toko Emas Palsu di Riau Dibongkar Polisi, Perh...","Rabu, 30 Jul 2025 22:22 WIB",https://news.detik.com/melindungi-tuah-marwah/...,Satreskrim Polres Bengkalis membongkar praktik...,pemalsuan emas,emas palsu,polres bengkalis,polda riau,melindungi tuah marwah,detik,"pemalsuan emas, emas palsu, polres bengkalis, ...",pemalsuan emas emas palsu polres bengkalis pol...,toko emas palsu di riau dibongkar polisi perhi...,satreskrim polres bengkalis membongkar praktik...
3,Minyakita Tak Sesuai Ukuran juga Ditemukan di ...,"Senin, 10 Mar 2025 23:15 WIB",https://news.detik.com/berita/d-7816829/minyak...,Polisi mendatangi salah satu gudang Minyakita ...,minyakita,kudus,NaN,NaN,NaN,detik,"minyakita, kudus",minyakita kudus,minyakita tak sesuai ukuran juga ditemukan di ...,polisi mendatangi salah satu gudang minyakita ...
4,"Pimpin LDP, Sanae Takaichi Calon Kuat PM Perem...",4 Oktober 2025 | 14.00 WIB,https://www.tempo.co/internasional/pimpin-ldp-...,"Baca berita dengan sedikit iklan, klik di sin...",jepang,perdana-menteri,sanae-takaichi,perempuan,ldp,tempo,"jepang, perdana-menteri, sanae-takaichi, perem...",jepang perdana menteri sanae takaichi perempua...,pimpin ldp sanae takaichi calon kuat pm peremp...,baca berita dengan sedikit iklan klik di sini ...

#### Klasifikasi Kategori

In [70]:
kamus_kategori = {
    'Bencana & Cuaca': [
        'gempa', 'tsunami', 'longsor', 'puting beliung', 'cuaca ekstrem',
        'hujan badai', 'erupsi', 'banjir bandang', 'kebakaran hutan',
        'karhutla', 'angin kencang', 'bencana alam', 'bnpb', 'evakuasi',
        'banjir susulan', 'tanggul jebol',
    ],
    'Kesehatan': [
        'rumah sakit', 'puskesmas', 'bpjs', 'pasien', 'dokter', 'obat',
        'wabah', 'stunting', 'demam berdarah', 'covid', 'vaksin',
        'kesehatan', 'gizi buruk', 'nakes', 'tenaga kesehatan',
        'apotek', 'faskes', 'posyandu',
    ],
    'Pendidikan': [
        'sekolah', 'guru', 'spp', 'zonasi', 'ppdb', 'kampus', 'mahasiswa',
        'beasiswa', 'kurikulum', 'ukt', 'siswa', 'pendidikan', 'ujian nasional',
        'sertifikasi guru', 'paud', 'literasi',
    ],
    'Air & Sanitasi': [
        'air bersih', 'pdam', 'krisis air', 'sanitasi', 'toilet', 'mck',
        'air keruh', 'kekeringan', 'air minum', 'sumur', 'irigasi',
        'kebocoran pipa', 'distribusi air',
    ],
    'Transportasi': [
        'macet', 'krl', 'mrt', 'angkot', 'busway', 'transjakarta',
        'stasiun', 'terminal', 'kecelakaan lalu lintas', 'kemacetan',
        'ojek online', 'ojol', 'gojek', 'grab', 'lrt', 'bis kota',
        'angkutan umum', 'parkir liar', 'tilang',
    ],
    'Keamanan & Sosial': [
        'maling', 'begal', 'tawuran', 'kriminalitas', 'polisi', 'keamanan',
        'demo', 'konflik warga', 'pencurian', 'penipuan', 'narkoba',
        'kejahatan', 'kekerasan', 'aksi massa', 'perjudian',
    ],
    'Pelayanan Publik': [
        'ktp', 'kk', 'dukcapil', 'paspor', 'birokrasi', 'pelayanan lambat',
        'pungli', 'sertifikat tanah', 'pelayanan publik', 'antrian panjang',
        'akta lahir', 'administrasi', 'kelurahan', 'kecamatan',
        'perizinan', 'izin usaha',
    ],
    'Infrastruktur & Jalan': [
        'jalan rusak', 'jembatan', 'aspal', 'berlubang', 'proyek jalan',
        'tol', 'gorong', 'trotoar', 'perbaikan jalan', 'jalan berlubang',
        'drainase', 'saluran air', 'infrastruktur', 'pembangunan jalan',
    ],
    'Ekonomi & UMKM': [
        'harga naik', 'sembako', 'inflasi', 'umkm', 'pasar', 'pedagang',
        'bantuan sosial', 'bansos', 'phk', 'pengangguran', 'upah minimum',
        'harga pangan', 'kemiskinan', 'kenaikan harga', 'bbm naik',
        'daya beli', 'ekonomi', 'investasi daerah',
    ],
    'Lingkungan & Sampah': [
        'sampah', 'tps', 'limbah', 'polusi', 'pencemaran', 'banjir',
        'sungai kotor', 'bau', 'berserakan', 'pengelolaan sampah',
        'tempat pembuangan', 'ruang hijau', 'penghijauan', 'illegal dumping',
    ],
}

In [71]:
def klasifikasi_berita(row):
    # Urutan prioritas: Tags -> Judul -> Isi Konten
    teks_untuk_dicek = [row['clean_tags'], row['clean_judul'], row['clean_konten']]

    for teks in teks_untuk_dicek:
        if teks: # Jika teksnya tidak kosong
            for kategori, kata_kunci in kamus_kategori.items():
                # Jika ada salah satu kata kunci yang cocok di dalam teks
                if any(kunci in teks for kunci in kata_kunci):
                    return kategori

    return 'Lainnya' # Jika tidak ada yang cocok sama sekali

In [72]:
df['kategori_isu'] = df.apply(klasifikasi_berita, axis=1)

print("Proses pembersihan dan klasifikasi selesai!")

Proses pembersihan dan klasifikasi selesai!

In [73]:
df[['Judul', 'kategori_isu']].head(10)

                                               Judul         kategori_isu
0  Viral Isu PHK Buruh Gudang Garam, Said Iqbal: ...       Ekonomi & UMKM
1         Gempa M 5,3 Guncang Pulau Doi Maluku Utara      Bencana & Cuaca
2  Toko Emas Palsu di Riau Dibongkar Polisi, Perh...    Keamanan & Sosial
3  Minyakita Tak Sesuai Ukuran juga Ditemukan di ...           Pendidikan
4  Pimpin LDP, Sanae Takaichi Calon Kuat PM Perem...    Keamanan & Sosial
5  Gubernur Banten Terpilih Andra Soni Temui Pres...            Kesehatan
6  Yusril: Pedemo Ditangkap Polisi karena Lakukan...    Keamanan & Sosial
7  Banjir Besar Landa Jabodetabek, Pimpinan MPR I...  Lingkungan & Sampah
8  Lagu "Indonesia Raya" Kena Royalti? Istana Men...              Lainnya
9  Remaja Ditindak Polisi di Serpong karena Bawa ...    Keamanan & Sosial

In [74]:
jumlah_kategori = df['kategori_isu'].value_counts()

print("=== Jumlah Data per Kategori ===")
print(jumlah_kategori)

=== Jumlah Data per Kategori ===
kategori_isu
Pendidikan               16388
Keamanan & Sosial        11794
Lainnya                  10462
Kesehatan                 7243
Pelayanan Publik          5848
Ekonomi & UMKM            4358
Transportasi              3532
Bencana & Cuaca           2665
Infrastruktur & Jalan     2501
Lingkungan & Sampah       2101
Air & Sanitasi             489
Name: count, dtype: int64

In [75]:
df.head()

,Judul,Waktu,Link,Content,tag1,tag2,tag3,tag4,tag5,source,all_tags,clean_tags,clean_judul,clean_konten,kategori_isu
0,"Viral Isu PHK Buruh Gudang Garam, Said Iqbal: ...",6 September 2025,https://nasional.kompas.com/read/2025/09/06/14...,"JAKARTA, KOMPAS.com – Presiden Konfederasi Se...",Said Iqbal,industri rokok,PT Gudang Garam,PHK massal,phk massal 2025 terbaru,kompas,"Said Iqbal, industri rokok, PT Gudang Garam, P...",said iqbal industri rokok pt gudang garam phk ...,viral isu phk buruh gudang garam said iqbal su...,jakarta kompas com presiden konfederasi serika...,Ekonomi & UMKM
1,"Gempa M 5,3 Guncang Pulau Doi Maluku Utara","Senin, 12 Agu 2024 21:58 WIB",https://news.detik.com/berita/d-7486691/gempa-...,"Gempa bumi berkekuatan magnitudo (M) 5,3 mengg...",pulau doi,gempa,NaN,NaN,NaN,detik,"pulau doi, gempa",pulau doi gempa,gempa m 5 3 guncang pulau doi maluku utara,gempa bumi berkekuatan magnitudo m 5 3 menggun...,Bencana & Cuaca
2,"Toko Emas Palsu di Riau Dibongkar Polisi, Perh...","Rabu, 30 Jul 2025 22:22 WIB",https://news.detik.com/melindungi-tuah-marwah/...,Satreskrim Polres Bengkalis membongkar praktik...,pemalsuan emas,emas palsu,polres bengkalis,polda riau,melindungi tuah marwah,detik,"pemalsuan emas, emas palsu, polres bengkalis, ...",pemalsuan emas emas palsu polres bengkalis pol...,toko emas palsu di riau dibongkar polisi perhi...,satreskrim polres bengkalis membongkar praktik...,Keamanan & Sosial
3,Minyakita Tak Sesuai Ukuran juga Ditemukan di ...,"Senin, 10 Mar 2025 23:15 WIB",https://news.detik.com/berita/d-7816829/minyak...,Polisi mendatangi salah satu gudang Minyakita ...,minyakita,kudus,NaN,NaN,NaN,detik,"minyakita, kudus",minyakita kudus,minyakita tak sesuai ukuran juga ditemukan di ...,polisi mendatangi salah satu gudang minyakita ...,Pendidikan
4,"Pimpin LDP, Sanae Takaichi Calon Kuat PM Perem...",4 Oktober 2025 | 14.00 WIB,https://www.tempo.co/internasional/pimpin-ldp-...,"Baca berita dengan sedikit iklan, klik di sin...",jepang,perdana-menteri,sanae-takaichi,perempuan,ldp,tempo,"jepang, perdana-menteri, sanae-takaichi, perem...",jepang perdana menteri sanae takaichi perempua...,pimpin ldp sanae takaichi calon kuat pm peremp...,baca berita dengan sedikit iklan klik di sini ...,Keamanan & Sosial

#### Filter Kategori 'Lainnya'

In [76]:
data_lainnya = df[df['kategori_isu'] == 'Lainnya']
print(data_lainnya[['Judul', 'clean_konten']].sample(50))

                                                   Judul  \
49072  Ribuan Desa di Kawasan Hutan, Adian: Persoalan...
50664  Penampilan Alicia Keys Hingga Shakira di Acara...
26701  Anies Tak Datang di Kampanye Akbar, Pramono: S...
35561  Prabowo: NU Punya Jasa Besar Terhadap Lahirnya...
55488  Menteri Irfan Yusuf Ingin Antrean Haji Disamar...
1967   DPR Pastikan Libatkan Masyakat dalam Pembahasa...
11119  KPK: Uang Non-budgeter Kasus BJB Mengalir ke M...
49464  Awasi Ujaran Kebencian di Pilkada 2024, Bawasl...
10150  Pansel Capim KPK Ungkap Alasan Tes Wawancara T...
59840  2 Penggugat Ancam Warisan Michael Jackson Rp 6...
49361  Open House di Istana, Masyarakat Boleh Bawa Po...
43555  Ganjar Sebut Hasto Masih Aktif Selaku Sekjen P...
44306  Daftar Jalan Ditutup dan Rute Alternatif Saat ...
55793  2 Bos Smelter Swasta yang Diwakili Harvey Moei...
56144     Link dan Cara Cek Pengumuman PPPK 2024 Tahap 2
23704  Prabowo Gelar Pertemuan dengan Ketua MPR dan S...
67725  Mikel Arteta Bicara Mimpi setelah Arsenal 5 Ta...
34241  Ridwan Kamil Nilai Semua Cagub Harus Bersinerg...
28202  Pramono Anung-Rano Karno Dinilai Memiliki Keha...
38361  Komnas HAM Usut Dugaan Pelanggaran HAM Program...
12535  Hunian di Kapal Pesiar Ini Dijual Seharga Rp 1...
66845  Pesan Pramono ke Paslon Lain di Pilkada Jakart...
67246  Gibran Pimpin Upacara Peringatan Hari Pahlawan...
26369  Bantah Minta Rp 100 Triliun untuk MBG, Kepala ...
8653   Jadwal Super League 2025/2026, Persebaya vs PS...
52196  Komentar Ole Romeny setelah Comeback di Laga T...
28594  Waka DPR Minta Lagu Kebangsaan Tak Dikenai Roy...
69002     Mutasi TNI, Marsma Deny Muis Jabat Dankopasgat
59505  Ini Alasan Instagram Beri Cincin Emas untuk 25...
77771  Libur Panjang Waisak, DAOP 9 Sediakan 40.678 T...
4127   Penyebab Konflik Iran-Israel dan Solusi Hunian...
56450                      Lukisan Garam di Tambak Lasem
74189  Memantau Proses Sortir dan Pelipatan Surat Sua...
47493  Muhammadiyah Yakin Kematian Ismail Haniyeh Tak...
65027  Hasto Kristiyanto: Saya Ikuti Seluruh Proses H...
59765  Menyesatkan: Video Sergap.id Soal Liputan Inve...
80228  KLH Awasi Intensif Kawasan Industri Modern Cik...
156    Cak Imin Ngaku Belum Pernah Ketemu Prabowo Bah...
3718   Depinas Soksi Dukung Bahlil Jadi Ketum Golkar ...
19140  Jokowi Puji Logo Baru PSI: Jadinya Seperti yan...
76452          Risiko Gula Turun Mutu dan Merugikan BUMN
62802  Saat Wisatawan Asal AS Terkesan dengan Pertunj...
58006  Penyeberangan ke Pulau Nusa Penida di Pelabuha...
905    Alasan Mutasi TNI Termasuk Letjen Kunto Anak T...
35570                   Lahirnya Generasi Baru Kutu Buku
49217  Sidang Kasus Timah, Ahli Sebut Kerusakan Lingk...
21963  3 Klub Liga 1 Umumkan Pelatih: Persijap, Persi...
58713  Nestapa Warga Penjaringan, Rumahnya Ludes Dila...
75688  Ditemani Cak Lontong "Jogging" di CFD, Pramono...
1914   KPUD Jakarta Serahkan Berkas Pengesahan Pramon...

                                            clean_konten
49072  jakarta kompas com anggota komisi v dpr ri adi...
50664  alicia keys berpose di karpet merah dalam acar...
26701  jakarta kompas com calon gubernur jakarta nomo...
35561  jakarta kompas com presiden republik indonesia...
55488  baca berita dengan sedikit iklan klik di sini ...
1967   jakarta kompas com mahkamah konstitusi mk tak ...
11119  kpk menyebut dana non budgeter dari kasus duga...
49464  baca berita dengan sedikit iklan klik di sini ...
10150  jakarta kompas com ketua panitia seleksi panse...
59840  baca berita dengan sedikit iklan klik di sini ...
49361  jakarta kompas com masyarakat umum yang hadir ...
43555  jakarta kompas com ketua dpp pdi perjuangan bi...
44306  jakarta kompas com dinas perhubungan dishub ja...
55793  dua petinggi pt refined bangka tin pt rbt yakn...
56144  baca berita dengan sedikit iklan klik di sini ...
23704  baca berita dengan sedikit iklan klik di sini ...
67725  baca berita dengan sedikit iklan klik di sini ...
34241  jakarta kompas com calon gubernur jakarta nomo...
28202  jakarta kompas com mantan ketua dprd jakarta p...
38361  jakarta kompas com komisi nasional hak asasi m...
12535  baca berita dengan sedikit iklan klik di sini ...
66845  jakarta kompas com calon gubernur jakarta pram...
67246  jakarta kompas com wakil presiden wapres gibra...
26369  jakarta kompas com kepala badan gizi nasional ...
8653   baca berita dengan sedikit iklan klik di sini ...
52196  baca berita dengan sedikit iklan klik di sini ...
28594  wakil ketua dpr ri cucun ahmad syamsurijal men...
69002  jakarta kompas com panglima tni jenderal tni a...
59505  baca berita dengan sedikit iklan klik di sini ...
77771  pt kai daop 9 jember jawa timur menyediakan 40...
4127   baca berita dengan sedikit iklan klik di sini ...
56450  baca berita dengan sedikit iklan klik di sini ...
74189  petugas menyortir dan melipat surat suara pilk...
47493  jakarta kompas com pimpinan pusat pp muhammadi...
65027  jakarta kompas com sekretaris jenderal pdi p h...
59765  baca berita dengan sedikit iklan klik di sini ...
80228  personel gegana brimob polri melakukan dekonta...
156    ketum pkb muhaimin iskandar atau cak imin meng...
3718   jakarta kompas com ketua umum dewan pimpinan n...
19140  presiden ke 7 ri joko widodo jokowi memuji log...
76452  baca berita dengan sedikit iklan klik di sini ...
62802  jakarta kompas com pertunjukan seni reog ponor...
58006  perahu tradisional di pelabuhan tribuana desa ...
905    panglima tni jenderal agus subiyanto merevisi ...
35570  baca berita dengan sedikit iklan klik di sini ...
49217  jakarta kompas com pakar pidana agus surono me...
21963  baca berita dengan sedikit iklan klik di sini ...
58713  jakarta kompas com ratusan rumah warga di kamp...
75688  jakarta kompas com bakal calon gubernur jakart...
1914   jakarta kompas com komisi pemilihan umum daera...

In [77]:
def bersihkan_artefak_redaksi(teks):
    """
    Menghapus penanda identitas media di awal teks seperti:
    - "Jakarta, Kompas.com - "
    - "ANTARA News - "
    - "Reporter: Nama - "
    - URL dan tanda baca standar (sudah ditangani bersihkan_teks())
    """
    if pd.isna(teks) or teks == "":
        return ""

    # Hapus pola "Kota, Nama_Media - " atau "Nama_Media - " di awal
    teks = re.sub(
        r'^[\w\s]+,\s*[\w\s\.]+\s*[-–]\s*',  # "Jakarta, Kompas.com - "
        '', teks, flags=re.IGNORECASE
    )
    # Hapus pola nama media standalone di awal: "ANTARA - ", "detikcom - "
    teks = re.sub(
        r'^(antara(\s*news)?|kompas\.?com|detik\.?com|tribun\w*|cnnindonesia|tempo\.?co'
        r'|republika|liputan6|okezone)\s*[-–]\s*',
        '', teks, flags=re.IGNORECASE
    )
    # Hapus pola "Reporter: Nama Wartawan - "
    teks = re.sub(r'^reporter\s*:\s*.+?[-–]\s*', '', teks, flags=re.IGNORECASE)
    # Hapus URL yang mungkin tersisa
    teks = re.sub(r'http\S+|www\S+|https\S+', '', teks)
    # Rapikan spasi
    teks = re.sub(r'\s+', ' ', teks).strip()
    return teks

# Terapkan ke kolom konten yang sudah di-clean sebelumnya
df['teks_bersih'] = df['Content'].apply(bersihkan_artefak_redaksi)
# Lalu terapkan cleaning standar (lowercase, hapus tanda baca, spasi)
df['teks_bersih'] = df['teks_bersih'].apply(bersihkan_teks)

print("Contoh hasil pembersihan artefak redaksi:")
print(df[['Content', 'teks_bersih']].head(3).to_string())

Contoh hasil pembersihan artefak redaksi:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        teks_bersih
0                                                                                                                                                                   JAKARTA, KOMPAS.com – Presiden Konfederasi Serikat Pekerja Indonesia (KSPI) Said Iqbal mengatakan, kabar pemutusan hubungan kerja (PHK) buruh pabrik rokok PT Gudang Garam bisa berdampak luas. Tidak hanya buruh pabrik, pekerja di sektor lain yang menggantungkan hidup pada industri rokok juga bisa terdampak. “Ribuan buruh rokok PT Gudang Garam ter-PHK, dan puluhan ribu buruh lainnya juga akan ter-PHK seperti buruh tembakau, logistik, sopir, pedagang kecil, suplier, pemilik kontrakan, dan lain-lain. Bisa jadi ratusan ribu buruh berpotensi kehilangan pekerjaan,” kata Said kepada Kompas.com, Sabtu (6/9/2025). Said Iqbal mengaku baru mendengar kabar PHK itu dan baru akan mengecek kebenarannya. Jika benar, KSPI meminta pemerintah pusat maupun daerah segera turun tangan untuk menyelamatkan industri rokok nasional dan melindungi para pekerja yang terancam kehilangan pekerjaan. “Tapi jangan seperti kasus PHK Sritex yang hanya janji manis, THR saja tidak dibayar,” kata dia. Media sosial sebelumnya diramaikan kabar PHK massal terhadap buruh pabrik rokok PT Gudang Garam di Tuban, Jawa Timur. Video pendek yang memperlihatkan suasana perpisahan para pekerja terdampak PHK menyebar luas dan memicu gelombang keprihatinan publik. Dalam rekaman itu, tampak puluhan karyawan saling berjabat tangan dengan suasana haru dan penuh kesedihan. Hingga Sabtu (6/9/2025), pihak PT Gudang Garam Tbk (GGRM) belum memberikan pernyataan resmi terkait kabar PHK massal ini. Sementara itu, perusahaan rokok mitra produksi PT Gudang Garam di Kabupaten Tuban, Jawa Timur, membantah terkait kabar pemutusan hubungan kerja (PHK) massal yang beredar di media sosial. Human Resources Development (HRD) PT Merdeka Nusantara Mitra Produksi Gudang Garam Tuban, Adib Musyafa mengatakan, kabar PHK massal karyawan Gudang Garam tersebut tidak terjadi di pabrik Tuban. "Sampai dengan saat ini, di Pabrik Tuban tidak ada PHK atau sejenisnya," kata Adib Musyafa, dikonfirmasi Kompas.com, Sabtu (6/9/2025). Adib Musyafa menyebutkan, produksi di pabrik Tuban saat ini juga masih terus berjalan normal dan sekitar 800 karyawan pabrik juga masih tetap bekerja seperti biasa. Pihaknya juga mengaku kaget mengetahui adanya pemberitaan PHK karyawan Gudang Garam di Tuban yang bersumber dari instagram atau media sosial.                                                                                                                                                                                presiden konfederasi serikat pekerja indonesia kspi said iqbal mengatakan kabar pemutusan hubungan kerja phk buruh pabrik rokok pt gudang garam bisa berdampak luas tidak hanya buruh pabrik pekerja di sektor lain yang menggantungkan hidup pada industri rokok juga bisa terdampak ribuan buruh rokok pt gudang garam ter phk dan puluhan ribu buruh lainnya juga akan ter phk seperti buruh tembakau logistik sopir pedagang kecil suplier pemilik kontrakan dan lain lain bisa jadi ratusan ribu buruh berpotensi kehilangan pekerjaan kata said kepada kompas com sabtu 6 9 2025 said iqbal mengaku baru mendengar kabar phk itu dan baru akan mengecek kebenarannya jika benar kspi meminta pemerintah pusat maupun daerah segera turun tangan untuk menyelamatkan industri rokok nasional dan melindungi para pekerja yang terancam kehilangan pekerjaan tapi jangan seperti kasus phk sritex yang hanya janji manis thr saja tidak dibayar kata dia media sosial sebelumnya diramaikan kabar phk massal terhadap buruh pabrik rokok pt gudang garam di tuban jawa timur video pendek yang memperlihatkan suasana perpisahan para pekerja terdampak phk menyebar luas dan memicu gelombang keprihatinan publik dalam rekaman itu tampak puluhan karyawan saling berjabat tangan dengan suasana haru dan penuh kesedihan hingga sabtu 6 9 2025 pihak pt gudang garam tbk ggrm belum memberikan pernyataan resmi terkait kabar phk massal ini sementara itu perusahaan rokok mitra produksi pt gudang garam di kabupaten tuban jawa timur membantah terkait kabar pemutusan hubungan kerja phk massal yang beredar di media sosial human resources development hrd pt merdeka nusantara mitra produksi gudang garam tuban adib musyafa mengatakan kabar phk massal karyawan gudang garam tersebut tidak terjadi di pabrik tuban sampai dengan saat ini di pabrik tuban tidak ada phk atau sejenisnya kata adib musyafa dikonfirmasi kompas com sabtu 6 9 2025 adib musyafa menyebutkan produksi di pabrik tuban saat ini juga masih terus berjalan normal dan sekitar 800 karyawan pabrik juga masih tetap bekerja seperti biasa pihaknya juga mengaku kaget mengetahui adanya pemberitaan phk karyawan gudang garam di tuban yang bersumber dari instagram atau media sosial
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Gempa bumi berkekuatan magnitudo (M) 5,3 mengguncang Kabupaten Pulau Doi, Maluku Utara. Gempa berada pada kedalaman 10 km. Informasi gempa ini disampaikan BMKG, dalam akun X resminya, Senin (12/7/2024). Disebutkan bahwa gempa terjadi pada pukul 18.36 WIB. "Pusat gempa berada di laut, 125 km barat laut Pulau Doi," tulis BMKG.  Titik gempa berada di koordinat 2,38 lintang utara dan 126,65 bujur timur. BMKG mengatakan informasi gempa yang diberikan mengutamakan kecepatan sehingga dapat terjadi perubahan data. Gempa dirasakan dengan skala Modified Mercalli Intensity (MMI) II-III di Tagulandang. Skala II artinya getaran dirasakan oleh beberapa orang, benda-benda ringan yang digantung bergoyang. Sementara skala III artinya getaran dirasakan nyata dalam rumah. Terasa getaran seakan-akan ada truk berlalu.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     gempa bumi berkekuatan magnitudo m 5 3 mengguncang kabupaten pulau doi maluku utara gempa berada pada kedalaman 10 km informasi gempa ini disampaikan bmkg dalam akun x resminya senin 12 7 2024 disebutkan bahwa gempa terjadi pada pukul 18 36 wib pusat gempa berada di laut 125 km barat laut pulau doi tulis bmkg titik gempa berada di koordinat 2 38 lintang utara dan 126 65 bujur timur bmkg mengatakan informasi gempa yang diberikan mengutamakan kecepatan sehingga dapat terjadi perubahan data gempa dirasakan dengan skala modified mercalli intensity mmi ii iii di tagulandang skala ii artinya getaran dirasakan oleh beberapa orang benda benda ringan yang digantung bergoyang sementara skala iii artinya getaran dirasakan nyata dalam rumah terasa getaran seakan akan ada truk berlalu
2  Satreskrim Polres Bengkalis membongkar praktik pemalsuan emas di sebuah toko di Pasar Mandau. Perhiasan emas palsu seberat 1,8 kilogram disita polisi dalam kasus tersebut. Kapolres Bengkalis AKBP Budi Setiawan mengatakan kasus ini terbongkar setelah pihaknya menerima laporan dari korban yang merasa dirugikan. Para korban membeli perhiasan dari toko tersebut sebagai investasi, namun ternyata emas itu palsu. "Para korban umumnya adalah warga pekerja keras-petani, nelayan, dan buruh sawit. Mereka membeli emas untuk dijadikan tabungan masa depan. Tapi yang mereka terima justru emas oplosan, emas palsu," ujar AKBP Budi kepada wartawan, Rabu (30/7/2025).  MI, pemilik toko emas yang berlokasi di Pasar Mandau, Jalan Jenderal Sudirman, Kelurahan Duri Timur, Kecamatan Mandau, diamankan polisi menyusul adanya laporan tersebut. "Saat ini pelaku diamankan di Mapolres Bengkalis untuk proses hukum lebih lanjut," imbuhnya. Polres Bengkalis awalnya menerima laporan dari korban berinisial AS (27) yang merasa dirugikan setelah membeli dua gelang emas seharga lebih dari Rp 4 juta. Setelah diperiksa di rumah, gelang tersebut menunjukkan tanda-tanda tidak sesuai standar emas, seperti tekstur lunak, warna kusam, dan tidak adanya kode emas.  Menindaklanjuti laporan tersebut, Satreskrim Polres Bekasi kemudian melakukan pengecekan ke toko emas tersebut. Dari lokasi, polisi menyita ratusan perhiasan emas palsu dengan berat total lebih dari 1,8 kilogram, cairan kimia, alat sepuh, timbangan digital, cap stempel, dan uang tunai. Sementara itu, Kasatreskrim Polres Bengkalis Iptu Yohn Mabel menyebut, pelaku mengakui telah menjual emas palsu. Modusnya adalah mencampur logam perak dan kemudian menyepuhnya agar tampak seperti emas murni, lalu dijual seolah-olah itu emas 22 karat. "Kami temukan berbagai jenis perhiasan seperti gelang, kalung, cincin, liontin hingga anting, serta alat-alat produksi dan dokumen pendukung," jelasnya. Dari hasil pemeriksaan awal, pelaku mengaku melakukan penipuan itu sejak tahun 2021. Saat ini sudah ada 4 orang yang melapor menjadi korban dari pemalsuan emas yang dilakukan pelaku MI, dan diperkirakan akan terus bertambah. MI saat ini diamankan di Polres Bengkalis. Dia dijerat dengan pasal 263 dan/atau pasal 378 KUHP tentang pemalsuan dan penipuan, dengan ancaman pidana maksimal enam tahun penjara.   Simak juga Video: Momen Penangkapan WNA China Penjual Emas Palsu di Bandar Lampung  [Gambas:Video 20detik]    satreskrim polres bengkalis membongkar praktik pemalsuan emas di sebuah toko di pasar mandau perhiasan emas palsu seberat 1 8 kilogram disita polisi dalam kasus tersebut kapolres bengkalis akbp budi setiawan mengatakan kasus ini terbongkar setelah pihaknya menerima laporan dari korban yang merasa dirugikan para korban membeli perhiasan dari toko tersebut sebagai investasi namun ternyata emas itu palsu para korban umumnya adalah warga pekerja keras petani nelayan dan buruh sawit mereka membeli emas untuk dijadikan tabungan masa depan tapi yang mereka terima justru emas oplosan emas palsu ujar akbp budi kepada wartawan rabu 30 7 2025 mi pemilik toko emas yang berlokasi di pasar mandau jalan jenderal sudirman kelurahan duri timur kecamatan mandau diamankan polisi menyusul adanya laporan tersebut saat ini pelaku diamankan di mapolres bengkalis untuk proses hukum lebih lanjut imbuhnya polres bengkalis awalnya menerima laporan dari korban berinisial as 27 yang merasa dirugikan setelah membeli dua gelang emas seharga lebih dari rp 4 juta setelah diperiksa di rumah gelang tersebut menunjukkan tanda tanda tidak sesuai standar emas seperti tekstur lunak warna kusam dan tidak adanya kode emas menindaklanjuti laporan tersebut satreskrim polres bekasi kemudian melakukan pengecekan ke toko emas tersebut dari lokasi polisi menyita ratusan perhiasan emas palsu dengan berat total lebih dari 1 8 kilogram cairan kimia alat sepuh timbangan digital cap stempel dan uang tunai sementara itu kasatreskrim polres bengkalis iptu yohn mabel menyebut pelaku mengakui telah menjual emas palsu modusnya adalah mencampur logam perak dan kemudian menyepuhnya agar tampak seperti emas murni lalu dijual seolah olah itu emas 22 karat kami temukan berbagai jenis perhiasan seperti gelang kalung cincin liontin hingga anting serta alat alat produksi dan dokumen pendukung jelasnya dari hasil pemeriksaan awal pelaku mengaku melakukan penipuan itu sejak tahun 2021 saat ini sudah ada 4 orang yang melapor menjadi korban dari pemalsuan emas yang dilakukan pelaku mi dan diperkirakan akan terus bertambah mi saat ini diamankan di polres bengkalis dia dijerat dengan pasal 263 dan atau pasal 378 kuhp tentang pemalsuan dan penipuan dengan ancaman pidana maksimal enam tahun penjara simak juga video momen penangkapan wna china penjual emas palsu di bandar lampung gambas video 20detik

In [78]:
jumlah_sebelum = len(df)
df = df[df['kategori_isu'] != 'Lainnya'].reset_index(drop=True)
jumlah_sesudah = len(df)

print(f"Baris dihapus (kategori 'Lainnya'): {jumlah_sebelum - jumlah_sesudah}")
print(f"Data tersisa: {jumlah_sesudah} baris")
print("\nDistribusi kategori setelah filter:")
print(df['kategori_isu'].value_counts())

Baris dihapus (kategori 'Lainnya'): 10462
Data tersisa: 56919 baris

Distribusi kategori setelah filter:
kategori_isu
Pendidikan               16388
Keamanan & Sosial        11794
Kesehatan                 7243
Pelayanan Publik          5848
Ekonomi & UMKM            4358
Transportasi              3532
Bencana & Cuaca           2665
Infrastruktur & Jalan     2501
Lingkungan & Sampah       2101
Air & Sanitasi             489
Name: count, dtype: int64

### Standardisasi

In [79]:
# STEP 1: Konversi tanggal DULU
def konversi_tanggal_berita(waktu):
    if pd.isna(waktu):
        return '2026-03-26'
    waktu = str(waktu).strip()
    bulan_map = {
        'Januari': 'January', 'Februari': 'February', 'Maret': 'March',
        'April': 'April', 'Mei': 'May', 'Juni': 'June',
        'Juli': 'July', 'Agustus': 'August', 'September': 'September',
        'Oktober': 'October', 'November': 'November', 'Desember': 'December'
    }
    for id_bulan, en_bulan in bulan_map.items():
        waktu = waktu.replace(id_bulan, en_bulan)
    waktu = re.sub(r'\s*\|.*$', '', waktu).strip()
    try:
        return pd.to_datetime(waktu, format='%d %B %Y').strftime('%Y-%m-%d')
    except:
        pass
    try:
        return pd.to_datetime(waktu, format='%d/%m/%Y').strftime('%Y-%m-%d')
    except:
        pass
    return '2026-03-26'

df['tanggal'] = df['Waktu'].apply(konversi_tanggal_berita)

# STEP 2: username
portal_mapping = {
    'kompas': '@kompascom', 'detik': '@detikcom', 'tribun': '@tribunews',
    'antara': '@antaranews', 'tempo': '@tempodotco', 'cnnindonesia': '@cnnindonesia',
    'republika': '@republikaonline', 'liputan6': '@liputan6dotcom', 'okezone': '@okezone',
}
def map_username(source):
    if pd.isna(source):
        return '@unknown'
    source_lower = str(source).lower()
    for key, val in portal_mapping.items():
        if key in source_lower:
            return val
    return f'@{source_lower.replace(" ", "")}'

df['username'] = df['source'].apply(map_username)

# STEP 3: Rakit df_berita_ready
df_berita_ready = pd.DataFrame({
    'sumber'         : 'berita_kaggle',
    'tanggal'        : df['tanggal'],
    'username'       : df['username'],
    'teks_bersih'    : df['teks_bersih'],
    'kategori_isu'   : df['kategori_isu'],
    'urgensi'        : 'Belum Dilabeli',
    'sentimen'       : 'Belum Dilabeli',
    'lokasi_insiden' : 'Belum diekstrak',
})

print("Shape DataFrame siap merge:", df_berita_ready.shape)
print(df_berita_ready['tanggal'].value_counts().head(10))
print(f"Imputasi: {(df_berita_ready['tanggal'] == '2026-03-26').sum()}")

Shape DataFrame siap merge: (56919, 8)
tanggal
2026-03-26    5634
2025-09-04     357
2025-10-02     337
2025-10-07     326
2025-10-17     326
2025-09-09     325
2025-10-20     325
2025-10-01     324
2025-09-23     323
2025-09-12     323
Name: count, dtype: int64
Imputasi: 5634

In [80]:
df_berita_ready.to_csv('berita_ready_to_merge.csv', index=False)
print("File 'berita_ready_to_merge.csv' berhasil disimpan!")
print(f"Total baris: {len(df_berita_ready)}")
print(f"Total kolom: {len(df_berita_ready.columns)}")

File 'berita_ready_to_merge.csv' berhasil disimpan!
Total baris: 56919
Total kolom: 8

In [81]:
print(df_berita_ready['kategori_isu'].value_counts())

kategori_isu
Pendidikan               16388
Keamanan & Sosial        11794
Kesehatan                 7243
Pelayanan Publik          5848
Ekonomi & UMKM            4358
Transportasi              3532
Bencana & Cuaca           2665
Infrastruktur & Jalan     2501
Lingkungan & Sampah       2101
Air & Sanitasi             489
Name: count, dtype: int64

### Sampling

In [82]:
# ============================================================
# SAMPLING FINAL: 1000 per kategori
# - Kategori > 1000 : undersample (random)
# - Kategori < 1000 : oversample (duplikasi acak)
# ============================================================

TARGET = 1000

def sample_kategori(group):
    n = len(group)
    if n >= TARGET:
        # Undersample
        return group.sample(n=TARGET, random_state=42)
    else:
        # Oversample: duplikasi acak sampai 1000
        extra = group.sample(n=TARGET - n, replace=True, random_state=42)
        return pd.concat([group, extra])

df_sampled = (
    df_berita_ready
    .groupby('kategori_isu', group_keys=False)
    .apply(sample_kategori)
    .reset_index(drop=True)
)

print("Distribusi setelah sampling:")
print(df_sampled['kategori_isu'].value_counts())
print(f"\nTotal data: {len(df_sampled)} baris")

Distribusi setelah sampling:
kategori_isu
Air & Sanitasi           1000
Bencana & Cuaca          1000
Ekonomi & UMKM           1000
Infrastruktur & Jalan    1000
Keamanan & Sosial        1000
Kesehatan                1000
Lingkungan & Sampah      1000
Pelayanan Publik         1000
Pendidikan               1000
Transportasi             1000
Name: count, dtype: int64

Total data: 10000 baris

/tmp/ipykernel_2867/44612533.py:22: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(sample_kategori)

In [83]:
# Export
df_sampled.to_csv('berita_ready_to_merge.csv', index=False)
print("File 'berita_ready_to_merge.csv' (final) berhasil disimpan!")

File 'berita_ready_to_merge.csv' (final) berhasil disimpan!

In [84]:
# Lihat 2 contoh teks per kategori
for kategori in df_sampled['kategori_isu'].unique():
    print(f"\n{'='*50}")
    print(f"KATEGORI: {kategori}")
    print('='*50)
    contoh = df_sampled[df_sampled['kategori_isu'] == kategori]['teks_bersih'].sample(2, random_state=42)
    for i, teks in enumerate(contoh, 1):
        print(f"{i}. {teks[:200]}")

==================================================
KATEGORI: Air & Sanitasi
==================================================
1. pt pelabuhan indonesia persero atau pelindo berjanji akan menambah toilet dan ruang tunggu yang layak di jakarta international container terminal jict usai didemo para sopir truk selain itu pelindo ju
2. pemerintah kota pemkot jakarta timur menertibkan fasilitas mandi cuci kakus mck liar yang mencemari lingkungan di wilayah rawa bunga kecamatan jatinegara minggu 3 8 2025 penertiban dilakukan bersamaan

==================================================
KATEGORI: Bencana & Cuaca
==================================================
1. pengendara motor bernama sahroni 56 tertabrak kereta api di kebon jeruk jakarta barat jakbar ia meninggal dunia di tempat ia mengalami luka pada bagian kepala pecah meninggal dunia di tkp ujar kasubdi
2. baca berita dengan sedikit iklan klik di sini tempo co jakarta wakil presiden wapres gibran rakabuming raka dijadwalkan akan meninjau korban erupsi gunung lewotobi laki laki flores nusa tenggara timur

==================================================
KATEGORI: Ekonomi & UMKM
==================================================
1. umat nonmuslim ikut berburu takjil viral di jalan raya mangga besar jakarta barat jumat 7 3 2025 pengamatan kompas com para pembeli terlihat menunggu kehadiran gerobak takjil yang akan tiba sekitar pu
2. pemerintah kota mojokerto memiliki cara sendiri dalam mewujudkan asta cita presiden prabowo subianto dan wakil presiden gibran rakabuming raka bahkan wali kota mojokerto ika puspitasari menjadikan ide

==================================================
KATEGORI: Infrastruktur & Jalan
==================================================
1. komisi pemberantasan korupsi kpk menyita satu unit apartemen senilai rp 500 juta yang berlokasi di tangerang selatan banten pada selasa 10 6 2025 pernyitaan tersebut terkait dengan kasus dugaan korups
2. presiden prabowo subianto menyerahkan daftar isian pelaksanaan anggaran dipa dan buku alokasi transfer ke daerah tkd tahun 2025 di istana negara kompleks istana kepresidenan jakarta pusat selasa 10 12

==================================================
KATEGORI: Keamanan & Sosial
==================================================
1. baca berita dengan sedikit iklan klik di sini kepolisian mengerahkan sebanyak 1 722 personel untuk mengamankan aksi bela palestina yang digelar di kawasan monumen nasional monas pada hari ini ahad 12
2. baca berita dengan sedikit iklan klik di sini tempo co jakarta polda sumatra utara sumut masih melakukan penyidikan kasus dugaan tindak pidana kekerasan dalam rumah tangga oleh brigadir devi maysari m

==================================================
KATEGORI: Kesehatan
==================================================
1. kompas com tanggal 9 oktober 2024 jatuh pada hari rabu pada tanggal ini terdapat peringatan atas terjadinya peristiwa geger pecinan selain itu terdapat pula peringatan dan perayaan lain pada hari ini
2. komisi perlindungan anak indonesia kpai terancam tidak bisa melakukan tugas pengawasan akibat adanya efisiensi anggaran dampaknya adalah kpai terancam tidak bisa melakukan tugas pengawasan ini to the

==================================================
KATEGORI: Lingkungan & Sampah
==================================================
1. hujan deras disertai angin kencang yang mengguyur kota tangerang pada selasa 12 8 2025 menyebabkan delapan titik tergenang banjir dan satu pohon tumbang kepala bidang kedaruratan dan logistik bpbd kot
2. wakil menteri lingkungan hidup lh diaz faisal malik hendropriyono cukup terkejut dengan banyaknya timbunan sampah saat menyusuri bantaran sungai ciliwung di kelurahan kedung halang kecamatan bogor uta

==================================================
KATEGORI: Pelayanan Publik
==================================================
1. pagi masih gelap ketika seorang sopir travel harus menghadapi kenyataan pahit di belakang kawasan mal season city jembatan besi tambora jakarta barat ia dihentikan oleh seorang pemuda yang dikenal war
2. menteri agama menag nasaruddin umar menyampaikan pesan perayaan imlek nasional di taman mini indonesia indah tmii jakarta nasaruddin menyebut setiap pemimpin pada lembaga apapun perlu lurus hati untuk

==================================================
KATEGORI: Pendidikan
==================================================
1. ketua badan pengawas pemilu bawaslu ri rahmat bagja mengatakan anggota dprd terpilih singkawang berinisial ha yang menjadi tersangka pencabulan bisa saja diganti namun penggantian atau penundaan pelan
2. baca berita dengan sedikit iklan klik di sini kasus kekerasan terhadap jurnalis terus berulang kali ini dialami empat awak redaksi dari papuanewsonline com mereka diduga dianiaya oleh kepala satuan re

==================================================
KATEGORI: Transportasi
==================================================
1. tmc polda metro jaya memprediksi kepadatan lalu lintas di sekitar kawasan gelora bung karno gbk senayan pada sabtu 12 4 2025 pukul 14 30 22 00 wib kepadatan lalu lintas tersebut terjadi karena lonjaka
2. kapolri jenderal listyo sigit prabowo memberikan perhatian khusus untuk tempat wisata yang berdekatan dengan laut atau bibir pantai karena ada ancaman bencana hidrometeorologi akibat cuaca buruk atens

### Load dan Standardisasi Data Twitter

In [85]:
# Load data Twitter (sudah dalam format blueprint)
df_twitter_ready = pd.read_csv('/content/drive/MyDrive/twitter_keluhan_clean.csv')

# Hapus baris kosong
df_twitter_ready = df_twitter_ready.dropna(subset=['kategori_isu', 'teks_bersih']).reset_index(drop=True)

print("Shape Twitter ready:", df_twitter_ready.shape)
print(df_twitter_ready['tanggal'].value_counts().head(5))
print(df_twitter_ready.head(3))

Shape Twitter ready: (1545, 8)
tanggal
2026-03-25    568
2026-03-26    469
2026-04-03    105
2026-03-28     81
2026-03-30     74
Name: count, dtype: int64
    sumber     tanggal         username  \
0  twitter  2026-03-25  @alung_koh21471
1  twitter  2026-03-25   @ciroalves2055
2  twitter  2026-03-25     @indrakusuma

                                         teks_bersih    kategori_isu  \
0  Koh Alung krisis air Pemerintah berupaya menan...  Air & Sanitasi
1  Rizki Fadillnaldo KRISIS AIR BERSIH? JANGAN AS...  Air & Sanitasi
2  Indra Kusuma air keruh Mangkanya doi dkk kecew...  Air & Sanitasi

          urgensi        sentimen   lokasi_insiden
0  Belum Dilabeli  Belum Dilabeli  Tidak diketahui
1  Belum Dilabeli  Belum Dilabeli  Tidak diketahui
2  Belum Dilabeli  Belum Dilabeli  Tidak diketahui

### Merge

In [86]:
df_gabungan = pd.concat([df_sampled, df_twitter_ready], ignore_index=True)

print("Shape gabungan:", df_gabungan.shape)
print("\nDistribusi sumber:")
print(df_gabungan['sumber'].value_counts())
print("\nDistribusi kategori:")
print(df_gabungan['kategori_isu'].value_counts())

Shape gabungan: (11545, 8)

Distribusi sumber:
sumber
berita_kaggle    10000
twitter           1545
Name: count, dtype: int64

Distribusi kategori:
kategori_isu
Infrastruktur & Jalan    1354
Ekonomi & UMKM           1290
Lingkungan & Sampah      1161
Pelayanan Publik         1151
Pendidikan               1149
Air & Sanitasi           1134
Transportasi             1098
Keamanan & Sosial        1097
Bencana & Cuaca          1074
Kesehatan                1037
Name: count, dtype: int64

In [87]:
# Cek apakah ada null setelah merge
print("\nNull values:")
print(df_gabungan.isnull().sum())

Null values:
sumber            0
tanggal           0
username          0
teks_bersih       0
kategori_isu      0
urgensi           0
sentimen          0
lokasi_insiden    0
dtype: int64

In [88]:
df_gabungan.to_csv('/content/drive/MyDrive/dataset_gabungan.csv', index=False)
print(f"Tersimpan di Google Drive!")
print(f"Total baris: {len(df_gabungan)}")
print(f"Kolom: {df_gabungan.columns.tolist()}")

Tersimpan di Google Drive!
Total baris: 11545
Kolom: ['sumber', 'tanggal', 'username', 'teks_bersih', 'kategori_isu', 'urgensi', 'sentimen', 'lokasi_insiden']

### Ringkasan Output

In [89]:
print("=" * 50)
print("RINGKASAN DATASET GABUNGAN")
print("=" * 50)
print(f"Total baris     : {len(df_gabungan)}")
print(f"Total kolom     : {len(df_gabungan.columns)}")
print(f"Kolom           : {df_gabungan.columns.tolist()}")
print()
print("Distribusi sumber:")
print(df_gabungan['sumber'].value_counts().to_string())
print()
print("Distribusi kategori:")
print(df_gabungan['kategori_isu'].value_counts().to_string())
print()
print("Null values:")
print(df_gabungan.isnull().sum().to_string())
print("=" * 50)
print("File tersimpan : dataset_gabungan.csv")

==================================================
RINGKASAN DATASET GABUNGAN
==================================================
Total baris     : 11545
Total kolom     : 8
Kolom           : ['sumber', 'tanggal', 'username', 'teks_bersih', 'kategori_isu', 'urgensi', 'sentimen', 'lokasi_insiden']

Distribusi sumber:
sumber
berita_kaggle    10000
twitter           1545

Distribusi kategori:
kategori_isu
Infrastruktur & Jalan    1354
Ekonomi & UMKM           1290
Lingkungan & Sampah      1161
Pelayanan Publik         1151
Pendidikan               1149
Air & Sanitasi           1134
Transportasi             1098
Keamanan & Sosial        1097
Bencana & Cuaca          1074
Kesehatan                1037

Null values:
sumber            0
tanggal           0
username          0
teks_bersih       0
kategori_isu      0
urgensi           0
sentimen          0
lokasi_insiden    0
==================================================
File tersimpan : dataset_gabungan.csv